// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XLITE_H
#define XLITE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xlite_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XLite_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XLite;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XLite_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XLite_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XLite_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XLite_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XLite_Initialize(XLite *InstancePtr, u16 DeviceId);
XLite_Config* XLite_LookupConfig(u16 DeviceId);
int XLite_CfgInitialize(XLite *InstancePtr, XLite_Config *ConfigPtr);
#else
int XLite_Initialize(XLite *InstancePtr, const char* InstanceName);
int XLite_Release(XLite *InstancePtr);
#endif

void XLite_Start(XLite *InstancePtr);
u32 XLite_IsDone(XLite *InstancePtr);
u32 XLite_IsIdle(XLite *InstancePtr);
u32 XLite_IsReady(XLite *InstancePtr);
void XLite_EnableAutoRestart(XLite *InstancePtr);
void XLite_DisableAutoRestart(XLite *InstancePtr);
u32 XLite_Get_return(XLite *InstancePtr);


void XLite_InterruptGlobalEnable(XLite *InstancePtr);
void XLite_InterruptGlobalDisable(XLite *InstancePtr);
void XLite_InterruptEnable(XLite *InstancePtr, u32 Mask);
void XLite_InterruptDisable(XLite *InstancePtr, u32 Mask);
void XLite_InterruptClear(XLite *InstancePtr, u32 Mask);
u32 XLite_InterruptGetEnabled(XLite *InstancePtr);
u32 XLite_InterruptGetStatus(XLite *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
