// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xlite.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XLite_CfgInitialize(XLite *InstancePtr, XLite_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XLite_Start(XLite *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLite_ReadReg(InstancePtr->Axilites_BaseAddress, XLITE_AXILITES_ADDR_AP_CTRL) & 0x80;
    XLite_WriteReg(InstancePtr->Axilites_BaseAddress, XLITE_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XLite_IsDone(XLite *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLite_ReadReg(InstancePtr->Axilites_BaseAddress, XLITE_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XLite_IsIdle(XLite *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLite_ReadReg(InstancePtr->Axilites_BaseAddress, XLITE_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XLite_IsReady(XLite *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLite_ReadReg(InstancePtr->Axilites_BaseAddress, XLITE_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XLite_EnableAutoRestart(XLite *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLite_WriteReg(InstancePtr->Axilites_BaseAddress, XLITE_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XLite_DisableAutoRestart(XLite *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLite_WriteReg(InstancePtr->Axilites_BaseAddress, XLITE_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XLite_Get_return(XLite *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLite_ReadReg(InstancePtr->Axilites_BaseAddress, XLITE_AXILITES_ADDR_AP_RETURN);
    return Data;
}
void XLite_InterruptGlobalEnable(XLite *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLite_WriteReg(InstancePtr->Axilites_BaseAddress, XLITE_AXILITES_ADDR_GIE, 1);
}

void XLite_InterruptGlobalDisable(XLite *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLite_WriteReg(InstancePtr->Axilites_BaseAddress, XLITE_AXILITES_ADDR_GIE, 0);
}

void XLite_InterruptEnable(XLite *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XLite_ReadReg(InstancePtr->Axilites_BaseAddress, XLITE_AXILITES_ADDR_IER);
    XLite_WriteReg(InstancePtr->Axilites_BaseAddress, XLITE_AXILITES_ADDR_IER, Register | Mask);
}

void XLite_InterruptDisable(XLite *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XLite_ReadReg(InstancePtr->Axilites_BaseAddress, XLITE_AXILITES_ADDR_IER);
    XLite_WriteReg(InstancePtr->Axilites_BaseAddress, XLITE_AXILITES_ADDR_IER, Register & (~Mask));
}

void XLite_InterruptClear(XLite *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLite_WriteReg(InstancePtr->Axilites_BaseAddress, XLITE_AXILITES_ADDR_ISR, Mask);
}

u32 XLite_InterruptGetEnabled(XLite *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XLite_ReadReg(InstancePtr->Axilites_BaseAddress, XLITE_AXILITES_ADDR_IER);
}

u32 XLite_InterruptGetStatus(XLite *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XLite_ReadReg(InstancePtr->Axilites_BaseAddress, XLITE_AXILITES_ADDR_ISR);
}

