# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/xujinyi/test/spartan_cam_2/spartan_cam/spartan_cam.srcs/sources_1/bd/system/ip/system_lite_0_0/system_lite_0_0.xci
# IP: The module: 'system_lite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/xujinyi/test/spartan_cam_2/spartan_cam/spartan_cam.srcs/sources_1/bd/system/ip/system_lite_0_0/constraints/lite_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_lite_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/xujinyi/test/spartan_cam_2/spartan_cam/spartan_cam.srcs/sources_1/bd/system/ip/system_lite_0_0/system_lite_0_0.xci
# IP: The module: 'system_lite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/xujinyi/test/spartan_cam_2/spartan_cam/spartan_cam.srcs/sources_1/bd/system/ip/system_lite_0_0/constraints/lite_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_lite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
